import type { FeaturedOffer, Trip } from "../types/travel";

export const featuredOffers: FeaturedOffer[] = [
  {
    id: "bali-signature",
    title: "Bali Signature Escape",
    destination: "Bali",
    duration: "7 nights",
    priceFrom: 1890,
    badge: "Best seller",
    accent: ["#235DFF", "#5F8EFF"],
    highlights: ["Beach villas", "Private transfers", "Sunset dining"],
  },
  {
    id: "alps-private",
    title: "Swiss Alps Private Retreat",
    destination: "Zermatt",
    duration: "5 nights",
    priceFrom: 2640,
    badge: "Luxury stay",
    accent: ["#071528", "#235DFF"],
    highlights: ["Mountain suites", "Spa access", "Scenic rail"],
  },
  {
    id: "tokyo-curated",
    title: "Tokyo Curated Discovery",
    destination: "Tokyo",
    duration: "6 nights",
    priceFrom: 2240,
    badge: "Editor pick",
    accent: ["#10213A", "#FF7A59"],
    highlights: ["Boutique stays", "City guide", "Priority booking"],
  },
  {
    id: "maldives-cove",
    title: "Maldives Private Cove",
    destination: "Maldives",
    duration: "6 nights",
    priceFrom: 3290,
    badge: "Oceanfront",
    accent: ["#0E375A", "#18A0C7"],
    highlights: ["Overwater villas", "Half board", "Lagoon spa"],
  },
  {
    id: "barcelona-family",
    title: "Barcelona Family Week",
    destination: "Barcelona",
    duration: "8 nights",
    priceFrom: 2150,
    badge: "Family favorite",
    accent: ["#10213A", "#FF9A3D"],
    highlights: ["City hotel", "Family rooms", "Museum passes"],
  },
  {
    id: "cappadocia-adventure",
    title: "Cappadocia Adventure Retreat",
    destination: "Cappadocia",
    duration: "4 nights",
    priceFrom: 1740,
    badge: "Adventure pick",
    accent: ["#40251A", "#D98052"],
    highlights: ["Cave suites", "Sunrise balloons", "Guided valleys"],
  },
];

export const upcomingTrips: Trip[] = [
  {
    id: "trip-1",
    title: "Dubai Weekend Escape",
    destination: "Dubai, UAE",
    endDate: "2026-04-16",
    status: "confirmed",
    startDate: "2026-04-12",
    progressLabel: "Hotel secured · Lounge included",
    travelers: 2,
  },
  {
    id: "trip-2",
    title: "Milan Design Circuit",
    destination: "Milan, Italy",
    endDate: "2026-05-10",
    status: "planning",
    startDate: "2026-05-04",
    progressLabel: "Heia is optimizing flights",
    travelers: 1,
  },
  {
    id: "trip-3",
    title: "Kyoto Autumn Journey",
    destination: "Kyoto, Japan",
    endDate: "2026-11-09",
    status: "wishlist",
    startDate: "2026-11-02",
    progressLabel: "Saved to premium shortlist",
    travelers: 2,
  },
];
